/**
 * Applies convention-based section metadata generated by generate-sections.ts.
 *
 * Reads the generated sectionMeta/syncComponents/loadingFallbacks and calls
 * the appropriate registration functions — replacing manual calls to
 * registerSectionsSync, setAsyncRenderingConfig, registerCacheableSections,
 * registerLayoutSections, registerSeoSections, and registerSection.
 */
import {
  registerSection,
  registerSectionsSync,
} from "./registry";
import {
  registerCacheableSections,
  registerLayoutSections,
} from "./sectionLoaders";
import {
  registerSeoSections,
  setAsyncRenderingConfig,
  getAsyncRenderingConfig,
} from "./resolve";

export interface SectionMetaEntry {
  eager?: boolean;
  cache?: string;
  layout?: boolean;
  sync?: boolean;
  clientOnly?: boolean;
  seo?: boolean;
  hasLoadingFallback?: boolean;
}

export interface ApplySectionConventionsInput {
  /** Section metadata map from sections.gen.ts */
  meta: Record<string, SectionMetaEntry>;
  /** Sync-imported section modules from sections.gen.ts */
  syncComponents?: Record<string, any>;
  /** LoadingFallback components from sections.gen.ts */
  loadingFallbacks?: Record<string, React.ComponentType<any>>;
  /** Lazy section loaders from import.meta.glob (used for clientOnly/loadingFallback registration) */
  sectionGlob?: Record<string, () => Promise<any>>;
}

export function applySectionConventions(input: ApplySectionConventionsInput): void {
  const { meta, syncComponents, loadingFallbacks, sectionGlob } = input;

  const eagerSections: string[] = [];
  const layoutSections: string[] = [];
  const seoSections: string[] = [];
  const cacheableSections: Record<string, string> = {};

  for (const [key, entry] of Object.entries(meta)) {
    if (entry.eager) eagerSections.push(key);
    if (entry.layout) layoutSections.push(key);
    if (entry.seo) seoSections.push(key);
    if (entry.cache) cacheableSections[key] = entry.cache;

    if (entry.clientOnly && sectionGlob) {
      const globKey = sectionGlobKey(key, sectionGlob);
      if (globKey) {
        registerSection(key, sectionGlob[globKey] as any, { clientOnly: true });
      }
    }

    if (entry.hasLoadingFallback && loadingFallbacks?.[key] && sectionGlob) {
      const globKey = sectionGlobKey(key, sectionGlob);
      if (globKey) {
        registerSection(key, sectionGlob[globKey] as any, {
          loadingFallback: loadingFallbacks[key],
        });
      }
    }
  }

  if (syncComponents && Object.keys(syncComponents).length > 0) {
    registerSectionsSync(syncComponents);
  }

  if (eagerSections.length > 0) {
    const existing = getAsyncRenderingConfig() ?? {};
    setAsyncRenderingConfig({
      ...existing,
      alwaysEager: [...(existing.alwaysEager ?? []), ...eagerSections],
    });
  }

  if (layoutSections.length > 0) {
    registerLayoutSections(layoutSections);
  }

  if (seoSections.length > 0) {
    registerSeoSections(seoSections);
  }

  if (Object.keys(cacheableSections).length > 0) {
    registerCacheableSections(cacheableSections);
  }
}

function sectionGlobKey(
  sectionKey: string,
  glob: Record<string, () => Promise<any>>,
): string | null {
  const relative = sectionKey.replace("site/sections/", "./sections/");
  if (glob[relative]) return relative;
  const withDot = sectionKey.replace("site/", "./");
  if (glob[withDot]) return withDot;
  return null;
}
