/**
 * CMS Route Helpers
 *
 * Reusable building blocks for CMS catch-all and homepage routes.
 * Since TanStack Router requires routes to be file-based in the site repo,
 * we export helper functions and config that sites use in their route files.
 *
 * @example Site's `src/routes/$.tsx`:
 * ```ts
 * import { createFileRoute, notFound } from "@tanstack/react-router";
 * import { loadCmsPage, cmsRouteConfig } from "@decocms/start/routes";
 * import { DecoPageRenderer } from "@decocms/start/hooks";
 *
 * export const Route = createFileRoute("/$")({
 *   ...cmsRouteConfig({
 *     siteName: "My Store",
 *     defaultTitle: "My Store - Best products",
 *     ignoreSearchParams: ["skuId"],
 *   }),
 * });
 * ```
 */

import { createServerFn } from "@tanstack/react-start";
import {
  getCookies,
  getRequest,
  getRequestHeader,
  getRequestUrl,
  setResponseHeader,
} from "@tanstack/react-start/server";
import { createElement } from "react";
import { loadCmsPagePure } from "../../core/cms/loadCmsPagePure";
import { preloadSectionComponents } from "../../core/cms/registry";
import type { MatcherContext, PageSeo, ResolvedSection } from "../../core/cms/resolve";
import { resolveDeferredSectionPure } from "../../core/cms/resolveDeferredSectionPure";
import {
  type CacheProfileName,
  cacheHeaders,
  routeCacheDefaults,
} from "../../core/sdk/cacheHeaders";
import { withTracing } from "../../core/sdk/observability";
import type { Device } from "../../core/sdk/useDevice";

const isServer = typeof document === "undefined";

// Section chunk manifest — maps section keys to chunk filenames.
// Generated by decoVitePlugin's generateBundle hook. Used to emit
// <link rel="modulepreload"> hints for eager sections.
let sectionChunkMap: Record<string, string> = {};

/**
 * Set the section chunk manifest. Called by the site's worker entry
 * or setup after loading the manifest.
 */
export function setSectionChunkMap(map: Record<string, string>): void {
  sectionChunkMap = map;
}

// ---------------------------------------------------------------------------
// Server function — loads a CMS page, runs section loaders, detects cache
// ---------------------------------------------------------------------------

type PageResult = Awaited<ReturnType<typeof loadCmsPageInternal>>;
const pageInflight = new Map<string, Promise<PageResult>>();

async function loadCmsPageInternal(fullPath: string) {
  const [basePath] = fullPath.split("?");
  const serverUrl = getRequestUrl();
  // Prefer the real server URL when available — it preserves duplicate query
  // params (e.g. filter.category-1=a&filter.category-1=b) that the TanStack
  // Router search object (plain Record<string,string>) would collapse.
  const realUrlPath = serverUrl.pathname + serverUrl.search;
  const urlWithSearch =
    realUrlPath.startsWith(basePath) && serverUrl.search
      ? serverUrl.toString()
      : fullPath.includes("?")
        ? new URL(fullPath, serverUrl.origin).toString()
        : serverUrl.toString();

  const originRequest = getRequest();
  const headers: Record<string, string> = {};
  for (const [k, v] of originRequest.headers.entries()) headers[k] = v;

  const matcherCtx: MatcherContext = {
    userAgent: getRequestHeader("user-agent") ?? "",
    url: urlWithSearch,
    path: basePath,
    cookies: getCookies(),
    headers,
    request: originRequest,
  };

  const result = await loadCmsPagePure(fullPath, matcherCtx);
  if (!result) return null;

  // Translate cacheMetadata into TanStack response headers. The pure loader
  // doesn't touch headers — that's the host's responsibility.
  if (result.cacheMetadata.cacheable) {
    if (result.cacheMetadata.cacheControl) {
      setResponseHeader("Cache-Control", result.cacheMetadata.cacheControl);
    }
  }

  // Strip cacheMetadata from the loader-data shape so SPA navigation payloads
  // stay identical to the pre-pure-extraction format.
  const { cacheMetadata: _cacheMetadata, ...pageData } = result;
  return pageData;
}

export const loadCmsPage = createServerFn({ method: "GET" })
  .inputValidator((data: unknown) => data as string)
  .handler(async (ctx) => {
    const fullPath = ctx.data;

    // Use the full path (including query string) as the dedup key.
    // Using basePath only caused /s?q=a and /s?q=b to share one promise,
    // returning wrong/empty results for search and filtered PLPs.
    const existing = pageInflight.get(fullPath);
    if (existing) return existing;

    const promise = loadCmsPageInternal(fullPath).finally(() => pageInflight.delete(fullPath));
    pageInflight.set(fullPath, promise);
    return promise;
  });

/**
 * Same as loadCmsPage but hardcoded to "/" path.
 * Avoids passing data through the server function for the homepage.
 */
export const loadCmsHomePage = createServerFn({ method: "GET" }).handler(async () => {
  const request = getRequest();
  const ua = getRequestHeader("user-agent") ?? "";
  const serverUrl = getRequestUrl();
  const headers: Record<string, string> = {};
  for (const [k, v] of request.headers.entries()) headers[k] = v;

  const matcherCtx: MatcherContext = {
    userAgent: ua,
    url: serverUrl.toString(),
    path: "/",
    cookies: getCookies(),
    headers,
    request,
  };

  const result = await loadCmsPagePure("/", matcherCtx);
  if (!result) return null;

  if (result.cacheMetadata.cacheable && result.cacheMetadata.cacheControl) {
    setResponseHeader("Cache-Control", result.cacheMetadata.cacheControl);
  }

  // Homepage payload historically omits `cacheProfile` (route headers handle it).
  const { cacheMetadata: _cm, cacheProfile: _cp, ...pageData } = result;
  return pageData;
});

// ---------------------------------------------------------------------------
// Deferred section loader — resolves + enriches a single section on demand
// ---------------------------------------------------------------------------

/**
 * @deprecated Prefer TanStack native streaming via `deferredPromises` in the
 * route loader. This POST server function is kept for backward compatibility
 * and as a fallback for SPA navigations.
 */
export const loadDeferredSection = createServerFn({ method: "POST" })
  .inputValidator(
    (data: unknown) =>
      data as {
        component: string;
        /** @deprecated rawProps are now resolved server-side from the deferred props cache. */
        rawProps?: Record<string, any>;
        pagePath: string;
        pageUrl?: string;
        /** Original position in the page section list — preserved for correct SPA ordering. */
        index?: number;
      },
  )
  .handler(async (ctx) => {
    const { component, rawProps: clientRawProps, pagePath, pageUrl, index } = ctx.data;

    const originRequest = getRequest();
    const serverUrl = getRequestUrl().toString();
    const headers: Record<string, string> = {};
    for (const [k, v] of originRequest.headers.entries()) headers[k] = v;

    const matcherCtx: MatcherContext = {
      userAgent: getRequestHeader("user-agent") ?? "",
      url: pageUrl || serverUrl,
      path: pagePath,
      cookies: getCookies(),
      headers,
      request: originRequest,
    };

    const result = await withTracing(
      "deco.section.deferred.load",
      () =>
        resolveDeferredSectionPure(pagePath, component, matcherCtx, {
          rawProps: clientRawProps,
          index,
        }),
      {
        "section.name": component,
        "page.path": pagePath,
        ...(typeof index === "number" ? { "section.index": index } : {}),
      },
    );
    if (!result) return null;

    // Translate cacheMetadata into TanStack response headers.
    // Without X-Deco-Cacheable, POST _serverFn responses are passed through
    // by the worker entry (checkout actions, invoke mutations, etc.).
    if (result.cacheMetadata.cacheable) {
      setResponseHeader("X-Deco-Cacheable", "true");
      if (result.cacheMetadata.cacheControl) {
        setResponseHeader("Cache-Control", result.cacheMetadata.cacheControl);
      }
    }

    return result.section;
  });

// ---------------------------------------------------------------------------
// Pre-wrapped deferred section loader for IntersectionObserver-based rendering
// ---------------------------------------------------------------------------

/**
 * Convenience wrapper around `loadDeferredSection` that matches the
 * `loadDeferredSectionFn` prop signature of `DecoPageRenderer`.
 *
 * Pass this directly to `<DecoPageRenderer loadDeferredSectionFn={deferredSectionLoader} />`
 * to enable IntersectionObserver-based lazy loading of deferred sections.
 */
export const deferredSectionLoader = async ({
  component,
  rawProps,
  pagePath,
  pageUrl,
  index,
}: {
  component: string;
  rawProps?: Record<string, unknown>;
  pagePath: string;
  pageUrl?: string;
  index?: number;
}): Promise<ResolvedSection | null> => {
  return loadDeferredSection({
    data: { component, rawProps, pagePath, pageUrl, index },
  });
};

// ---------------------------------------------------------------------------
// Default pending component — shown during SPA navigation while loader runs
// ---------------------------------------------------------------------------

export function CmsPagePendingFallback() {
  return createElement(
    "div",
    { className: "w-full min-h-[60vh] flex flex-col gap-6 py-8" },
    createElement("div", {
      className: "skeleton animate-pulse w-full rounded",
      style: { aspectRatio: "1440/400", minHeight: 200 },
    }),
    createElement(
      "div",
      { className: "px-4 lg:px-8 flex flex-col gap-4" },
      createElement("div", { className: "skeleton animate-pulse w-48 h-8 rounded" }),
      createElement(
        "div",
        { className: "grid grid-cols-2 lg:grid-cols-4 gap-4" },
        ...Array.from({ length: 4 }, (_, i) =>
          createElement("div", {
            key: i,
            className: "skeleton animate-pulse w-full h-48 lg:h-64 rounded",
          }),
        ),
      ),
    ),
  );
}

// ---------------------------------------------------------------------------
// Route configuration factory
// ---------------------------------------------------------------------------

export interface CmsRouteOptions {
  /** Site name used in page titles (e.g. "Espaço Smart"). */
  siteName: string;
  /** Default page title when CMS page has no name. */
  defaultTitle: string;
  /** Default description for pages without section-contributed SEO. */
  defaultDescription?: string;
  /**
   * Search params to exclude from loader deps.
   * These params won't trigger a server re-fetch when they change.
   * Defaults to `["skuId"]` — variant selection is client-side only.
   */
  ignoreSearchParams?: string[];
  /** Custom pending component shown during SPA navigation. */
  pendingComponent?: () => any;
  /**
   * Delay (ms) before showing the pending component during SPA navigation.
   * If the loader resolves before this threshold, no pending UI is shown.
   * Prevents skeleton flash on fast cache-hit navigations. Default: 200.
   */
  pendingMs?: number;
  /**
   * Minimum display time (ms) for the pending component once shown.
   * Prevents jarring flash when data arrives shortly after the threshold.
   * Default: 300.
   */
  pendingMinMs?: number;
  /**
   * SSR mode for this route.
   * - `true` (default): Full SSR — loader + component render on server.
   * - `'data-only'`: Loader runs on server, component renders on client only.
   *   Use for interactive-heavy pages (PDP with zoom/variant selector).
   * - `false`: Everything runs on client only.
   */
  ssr?: boolean | "data-only";
}

type CmsPageLoaderData = {
  name?: string;
  cacheProfile?: CacheProfileName;
  seo?: PageSeo;
  device?: Device;
  resolvedSections?: Array<{ component: string }>;
} | null;

// ---------------------------------------------------------------------------
// Head metadata builder
// ---------------------------------------------------------------------------

/**
 * Build TanStack Router `head()` metadata from page-level and section-contributed SEO.
 * Emits: title, description, canonical, OG tags, Twitter Card, robots directive.
 */
function buildHead(
  loaderData: CmsPageLoaderData | undefined,
  siteName: string,
  defaultTitle: string,
  defaultDescription?: string,
) {
  const seo = loaderData?.seo;
  const title = seo?.title
    ? seo.title
    : loaderData?.name
      ? `${loaderData.name} | ${siteName}`
      : defaultTitle;
  const description = seo?.description || defaultDescription;
  const image = seo?.image;
  const canonical = seo?.canonical;
  const noIndex = seo?.noIndexing;

  const meta: Record<string, string>[] = [{ title }];

  if (description) {
    meta.push({ name: "description", content: description });
  }

  // Robots — always emit a directive so crawlers see an explicit signal
  meta.push({
    name: "robots",
    content: noIndex
      ? "noindex, nofollow"
      : "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
  });

  // Open Graph
  meta.push({ property: "og:title", content: title });
  if (description) meta.push({ property: "og:description", content: description });
  if (image) meta.push({ property: "og:image", content: image });
  meta.push({ property: "og:type", content: seo?.type || "website" });
  if (canonical) meta.push({ property: "og:url", content: canonical });

  // Twitter Card
  meta.push({ name: "twitter:card", content: image ? "summary_large_image" : "summary" });
  meta.push({ name: "twitter:title", content: title });
  if (description) meta.push({ name: "twitter:description", content: description });
  if (image) meta.push({ name: "twitter:image", content: image });

  const links: Record<string, string>[] = [];
  if (canonical) {
    links.push({ rel: "canonical", href: canonical });
  }

  // Modulepreload hints for eager section chunks
  if (loaderData?.resolvedSections) {
    for (const s of loaderData.resolvedSections) {
      const chunkFile = sectionChunkMap[s.component];
      if (chunkFile) {
        links.push({ rel: "modulepreload", href: `/${chunkFile}` });
      }
    }
  }

  // JSON-LD structured data — rendered as <script type="application/ld+json"> in <head>
  const scripts: Array<{ type: string; children: string }> = [];
  if (seo?.jsonLDs?.length) {
    for (const jsonLD of seo.jsonLDs) {
      scripts.push({
        type: "application/ld+json",
        children: JSON.stringify(jsonLD),
      });
    }
  }

  return { meta, links, scripts };
}

/**
 * Returns a TanStack Router route config object for a CMS catch-all route.
 * Spread the result into your `createFileRoute("/$")({...})` call.
 *
 * Includes: loaderDeps, loader, headers, head (with full SEO), staleTime/gcTime.
 * Does NOT include: component, notFoundComponent (site provides these).
 *
 * SEO metadata is extracted from sections registered via `registerSeoSections()`.
 * The `head()` function emits title, description, canonical, OG tags, and robots.
 */
export function cmsRouteConfig(options: CmsRouteOptions) {
  const {
    siteName,
    defaultTitle,
    defaultDescription,
    ignoreSearchParams = ["skuId"],
    pendingComponent,
    pendingMs = 200,
    pendingMinMs = 300,
    ssr: ssrMode,
  } = options;

  const ignoreSet = new Set(ignoreSearchParams);

  return {
    // Catch-all search validation: preserve all URL search params so they
    // reach loaderDeps. Without this, TanStack Router may strip unknown
    // params (e.g. ?q=, filter.*, page, sort) during SPA navigation.
    validateSearch: (search: Record<string, unknown>) => search as Record<string, string>,

    loaderDeps: ({ search }: { search: Record<string, string> }) => {
      const filtered = Object.fromEntries(
        Object.entries(search ?? {}).filter(([k]) => !ignoreSet.has(k)),
      );
      return {
        search: Object.keys(filtered).length ? filtered : undefined,
      };
    },

    loader: async ({
      params,
      deps,
    }: {
      params: { _splat?: string };
      deps: { search?: Record<string, string> };
    }) => {
      const basePath = "/" + (params._splat || "");
      const searchStr = deps.search
        ? "?" + new URLSearchParams(deps.search as Record<string, string>).toString()
        : "";
      const page = await loadCmsPage({ data: basePath + searchStr });
      if (!page) return page;

      if (!isServer && page.resolvedSections) {
        const keys = page.resolvedSections.map((s: ResolvedSection) => s.component);
        await preloadSectionComponents(keys);
      }

      // Deferred sections use client-side IntersectionObserver loading.
      // DecoPageRenderer renders skeletons (LoadingFallback) during SSR and
      // loads full section content via _serverFn when scrolled into view.
      //
      // Previously, SSR streaming via TanStack <Await> resolved ALL deferred
      // sections server-side and streamed them in the initial HTML. This caused
      // the browser to load ALL product shelf images at once (~3x more image
      // requests than the IntersectionObserver path). Client SPA navigation
      // also blocked on await Promise.all() for all deferred sections.
      //
      // The IO path (DeferredSectionWrapper) only fetches section data when
      // the skeleton scrolls into view, matching Fresh/Deno partial behavior
      // and significantly reducing initial image load and TBT.
      return page;
    },

    ...(pendingComponent ? { pendingComponent } : {}),
    pendingMs,
    pendingMinMs,
    ...(ssrMode !== undefined ? { ssr: ssrMode } : {}),

    ...routeCacheDefaults("product"),

    headers: ({ loaderData }: { loaderData?: CmsPageLoaderData }) => {
      const profile = loaderData?.cacheProfile ?? "listing";
      return cacheHeaders(profile);
    },

    head: ({ loaderData }: { loaderData?: CmsPageLoaderData }) =>
      buildHead(loaderData, siteName, defaultTitle, defaultDescription),
  };
}

/**
 * Returns a TanStack Router route config for the CMS homepage route.
 * Spread into `createFileRoute("/")({...})`.
 *
 * Like `cmsRouteConfig`, emits full SEO head metadata from section-contributed data.
 */
export function cmsHomeRouteConfig(options: {
  defaultTitle: string;
  defaultDescription?: string;
  /** Site name for OG title composition. Defaults to defaultTitle. */
  siteName?: string;
  pendingComponent?: () => any;
  /** Delay (ms) before showing pending component. Default: 200. */
  pendingMs?: number;
  /** Minimum display time (ms) for pending component. Default: 300. */
  pendingMinMs?: number;
}) {
  const {
    defaultTitle,
    defaultDescription,
    siteName,
    pendingMs = 200,
    pendingMinMs = 300,
  } = options;

  return {
    loader: async () => {
      const page = await loadCmsHomePage();
      if (!page) return page;

      if (!isServer && page.resolvedSections) {
        const keys = page.resolvedSections.map((s: ResolvedSection) => s.component);
        await preloadSectionComponents(keys);
      }

      // Deferred sections use client-side IntersectionObserver loading.
      // See cmsRouteConfig loader for rationale.
      return page;
    },
    ...(options.pendingComponent ? { pendingComponent: options.pendingComponent } : {}),
    pendingMs,
    pendingMinMs,
    ...routeCacheDefaults("static"),
    headers: () => cacheHeaders("static"),
    head: ({ loaderData }: { loaderData?: CmsPageLoaderData }) =>
      buildHead(loaderData, siteName ?? defaultTitle, defaultTitle, defaultDescription),
  };
}
