/**
 * Compat module barrel export.
 * Provides all shims needed to bridge Deco's Preact/Fresh-based components
 * to React/TanStack Start.
 *
 * Consumers use these via Vite resolve aliases generated by getViteAliases().
 */
export * from "./signals";
export * from "./deco";
export * from "./deco-hooks";
export * from "./deco-blocks";
export * from "./deco-o11y";
export * from "./fresh-runtime";
export * from "./widgets";
