#!/usr/bin/env node
// deco-wrangler
//
// Local-dev wrapper around `wrangler` for storefront repos that no longer
// commit a `wrangler.jsonc`. Generates the canonical config from
// `@decocms/start`'s registry into `./wrangler.jsonc` (gitignored), then
// optionally execs the real `wrangler` with that config in cwd.
//
// Usage from a customer repo (after `npm i -D @decocms/start@latest`):
//
//   npx deco-wrangler gen          # generate ./wrangler.jsonc and exit
//                                  # (used by predev/prebuild/prepare hooks)
//   npx deco-wrangler tail         # tail prod logs (worker name resolved automatically)
//   npx deco-wrangler types        # regenerate worker-configuration.d.ts
//   npx deco-wrangler deploy       # discouraged in dev; deploys go via CI
//   npx deco-wrangler --help       # passes through to wrangler
//
// All non-`gen` invocations also (re)generate ./wrangler.jsonc first so the
// file is always in sync with the registry before wrangler runs. The
// `@cloudflare/vite-plugin` and the `wrangler` CLI both auto-discover
// ./wrangler.jsonc in cwd, so no extra config plumbing is required.
//
// Site identity (which entry of `deploy/sites/` to load) resolves in this
// order:
//
//   1. DECO_SITE_NAME env var (explicit override)
//   2. git remote `origin` URL parsed for the GitHub repo name
//   3. package.json `name` field
//
// Fails loudly if none of these match a registered site -- no implicit "guess
// the worker" behavior. The local wrapper enforces the same trust model the CI
// pipeline does.

import { execSync, spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSiteManifest, loadTemplate, mergeWithTemplate } from "./site-registry.mjs";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
// scripts/deploy/wrangler-wrapper.mjs -> deco-start root
const DECO_START_PATH = resolve(SCRIPT_DIR, "..", "..");

function eprintln(msg) {
  process.stderr.write(`[deco-wrangler] ${msg}\n`);
}

function tryGitRemoteSiteName() {
  try {
    const url = execSync("git remote get-url origin", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    // matches both git@github.com:org/repo(.git) and https://github.com/org/repo(.git)
    const m = url.match(/github\.com[:/][^/]+\/([^/]+?)(?:\.git)?$/);
    return m?.[1];
  } catch {
    return undefined;
  }
}

function tryPackageJsonName() {
  try {
    const pkg = JSON.parse(readFileSync(resolve(process.cwd(), "package.json"), "utf8"));
    return typeof pkg.name === "string" ? pkg.name : undefined;
  } catch {
    return undefined;
  }
}

function resolveSiteName() {
  const envName = process.env.DECO_SITE_NAME?.trim();
  if (envName) return { name: envName, source: "DECO_SITE_NAME env var" };
  const gitName = tryGitRemoteSiteName();
  if (gitName) return { name: gitName, source: "git remote origin" };
  const pkgName = tryPackageJsonName();
  if (pkgName) return { name: pkgName, source: "package.json name" };
  return undefined;
}

const resolved = resolveSiteName();
if (!resolved) {
  eprintln(
    "Could not determine site name. Set DECO_SITE_NAME or run from a repo with a github.com 'origin' remote.",
  );
  process.exit(1);
}

let manifest;
try {
  manifest = loadSiteManifest(DECO_START_PATH, resolved.name);
} catch (err) {
  eprintln(err instanceof Error ? err.message : String(err));
  eprintln(`Site name "${resolved.name}" was inferred from ${resolved.source}.`);
  eprintln(
    `If this is a personal sandbox, set DECO_SITE_NAME=<registered-site> or open a PR to deco-start adding deploy/sites/${resolved.name}.jsonc.`,
  );
  process.exit(1);
}

const merged = mergeWithTemplate(loadTemplate(DECO_START_PATH), manifest);

const outputPath = resolve(process.cwd(), "wrangler.jsonc");
const header = `// AUTOGENERATED by deco-wrangler -- DO NOT COMMIT.
// Add wrangler.jsonc to .gitignore. Regenerated on every \`deco-wrangler\` run.
// Source: @decocms/start deploy/sites/${resolved.name}.jsonc + wrangler-template.jsonc
`;
writeFileSync(outputPath, `${header}${JSON.stringify(merged, null, 2)}\n`);

eprintln(
  `Resolved site "${resolved.name}" -> worker "${manifest.worker_name}" (via ${resolved.source})`,
);
eprintln(`Generated ${outputPath}`);

const argv = process.argv.slice(2);
// `gen` mode: just write the config and exit. Used by package.json
// predev/prebuild/prepare hooks to keep wrangler.jsonc in sync with the
// registry without invoking wrangler itself.
if (argv[0] === "gen" || argv[0] === "generate") {
  process.exit(0);
}

const wranglerArgs = ["wrangler", ...argv];
const result = spawnSync("npx", wranglerArgs, { stdio: "inherit" });
process.exit(result.status ?? 1);
