#!/usr/bin/env node
// deco-wrangler
//
// Local-dev wrapper around `wrangler` for storefront repos that no longer
// commit a `wrangler.jsonc`. Generates the canonical config from
// `@decocms/start`'s template into `./wrangler.jsonc` (gitignored), then
// optionally execs the real `wrangler` with that config in cwd.
//
// Usage from a customer repo (after `npm i -D @decocms/start@latest`):
//
//   npx deco-wrangler gen          # generate ./wrangler.jsonc and exit
//                                  # (used by predev/prebuild/prepare hooks)
//   npx deco-wrangler tail         # tail prod logs (worker name resolved automatically)
//   npx deco-wrangler types        # regenerate worker-configuration.d.ts
//   npx deco-wrangler deploy       # discouraged in dev; deploys go via CI
//   npx deco-wrangler --help       # passes through to wrangler
//
// All non-`gen` invocations also (re)generate ./wrangler.jsonc first so the
// file is always in sync with the template before wrangler runs. The
// `@cloudflare/vite-plugin` and the `wrangler` CLI both auto-discover
// ./wrangler.jsonc in cwd, so no extra config plumbing is required.
//
// Worker name resolves in this order:
//
//   1. DECO_WORKER_NAME env var (explicit override)
//   2. git remote `origin` URL parsed for the GitHub repo basename
//   3. package.json `name` field
//
// By convention worker name == storefront repo basename. The CI deploys use
// the same convention. Local dev never deploys -- this wrapper is purely for
// generating a config that matches what the central workflow will produce.

import { execSync, spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { applyWorkerName, loadTemplate } from "./site-registry.mjs";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
// scripts/deploy/wrangler-wrapper.mjs -> deco-start root
const DECO_START_PATH = resolve(SCRIPT_DIR, "..", "..");

function eprintln(msg) {
  process.stderr.write(`[deco-wrangler] ${msg}\n`);
}

function tryGitRemoteWorkerName() {
  try {
    const url = execSync("git remote get-url origin", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    // matches both git@github.com:org/repo(.git) and https://github.com/org/repo(.git)
    const m = url.match(/github\.com[:/][^/]+\/([^/]+?)(?:\.git)?$/);
    return m?.[1];
  } catch {
    return undefined;
  }
}

function tryPackageJsonName() {
  try {
    const pkg = JSON.parse(readFileSync(resolve(process.cwd(), "package.json"), "utf8"));
    return typeof pkg.name === "string" ? pkg.name : undefined;
  } catch {
    return undefined;
  }
}

function resolveWorkerName() {
  const envName = process.env.DECO_WORKER_NAME?.trim();
  if (envName) return { name: envName, source: "DECO_WORKER_NAME env var" };
  const gitName = tryGitRemoteWorkerName();
  if (gitName) return { name: gitName, source: "git remote origin" };
  const pkgName = tryPackageJsonName();
  if (pkgName) return { name: pkgName, source: "package.json name" };
  return undefined;
}

const resolved = resolveWorkerName();
if (!resolved) {
  eprintln(
    "Could not determine worker name. Set DECO_WORKER_NAME or run from a repo with a github.com 'origin' remote.",
  );
  process.exit(1);
}

let merged;
try {
  merged = applyWorkerName(loadTemplate(DECO_START_PATH), resolved.name);
} catch (err) {
  eprintln(err instanceof Error ? err.message : String(err));
  eprintln(`Worker name "${resolved.name}" was inferred from ${resolved.source}.`);
  process.exit(1);
}

const outputPath = resolve(process.cwd(), "wrangler.jsonc");
const header = `// AUTOGENERATED by deco-wrangler -- DO NOT COMMIT.
// Add wrangler.jsonc to .gitignore. Regenerated on every \`deco-wrangler\` run.
// Source: @decocms/start deploy/wrangler-template.jsonc + worker name "${resolved.name}"
`;
writeFileSync(outputPath, `${header}${JSON.stringify(merged, null, 2)}\n`);

eprintln(`Resolved worker name "${resolved.name}" (via ${resolved.source})`);
eprintln(`Generated ${outputPath}`);

const argv = process.argv.slice(2);
// `gen` mode: just write the config and exit. Used by package.json
// predev/prebuild/prepare hooks to keep wrangler.jsonc in sync with the
// template without invoking wrangler itself.
if (argv[0] === "gen" || argv[0] === "generate") {
  process.exit(0);
}

const wranglerArgs = ["wrangler", ...argv];
const result = spawnSync("npx", wranglerArgs, { stdio: "inherit" });
process.exit(result.status ?? 1);
