#!/usr/bin/env tsx
/**
 * Scans site section files and extracts convention-based metadata:
 *   - export const eager = true       → alwaysEager
 *   - export const cache = "listing"  → registerCacheableSections
 *   - export const layout = true      → registerLayoutSections
 *   - export const sync = true        → registerSectionsSync (bundled, not lazy)
 *   - export const clientOnly = true  → registerSection with clientOnly
 *   - export const seo = true         → registerSeoSections
 *   - export function LoadingFallback → registerSection with loadingFallback
 *
 * Emits sections.gen.ts with metadata + sync imports for sections marked sync=true.
 *
 * Usage (from site root):
 *   npx tsx node_modules/@decocms/start/scripts/generate-sections.ts
 *
 * CLI:
 *   --sections-dir  override input  (default: src/sections)
 *   --out-file      override output (default: src/server/cms/sections.gen.ts)
 */
import fs from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);
function arg(name: string, fallback: string): string {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : fallback;
}

const sectionsDir = path.resolve(process.cwd(), arg("sections-dir", "src/sections"));
const outFile = path.resolve(process.cwd(), arg("out-file", "src/server/cms/sections.gen.ts"));

interface SectionMeta {
  eager?: boolean;
  cache?: string;
  layout?: boolean;
  sync?: boolean;
  clientOnly?: boolean;
  seo?: boolean;
  hasLoadingFallback?: boolean;
}

const EXPORT_CONST_RE = /export\s+const\s+(eager|cache|layout|sync|clientOnly|seo)\s*=\s*(.+?)(?:;|\n)/g;
const LOADING_FALLBACK_RE = /export\s+(?:function|const)\s+LoadingFallback\b/;

function extractMeta(content: string): SectionMeta | null {
  const meta: SectionMeta = {};
  let found = false;

  for (const match of content.matchAll(EXPORT_CONST_RE)) {
    const key = match[1] as keyof SectionMeta;
    const rawValue = match[2].trim().replace(/['"]/g, "");
    found = true;

    if (key === "cache") {
      meta.cache = rawValue;
    } else if (rawValue === "true") {
      (meta as any)[key] = true;
    }
  }

  if (LOADING_FALLBACK_RE.test(content)) {
    meta.hasLoadingFallback = true;
    found = true;
  }

  return found ? meta : null;
}

function walkDir(dir: string, base: string = dir): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(fullPath, base));
    } else if (entry.name.endsWith(".tsx") || entry.name.endsWith(".ts")) {
      results.push(fullPath);
    }
  }
  return results;
}

function fileToSectionKey(filePath: string, _sectionsDir: string): string {
  const rel = path.relative(_sectionsDir, filePath).replace(/\\/g, "/");
  return `site/sections/${rel}`;
}

function relativeImportPath(from: string, to: string): string {
  let rel = path.relative(path.dirname(from), to).replace(/\\/g, "/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel.replace(/\.tsx?$/, "");
}

// ---------------------------------------------------------------------------

if (!fs.existsSync(sectionsDir)) {
  console.warn(`Sections directory not found: ${sectionsDir} — generating empty output.`);
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, [
    "// Auto-generated — no sections found.",
    "export const sectionMeta = {};",
    "",
  ].join("\n"));
  process.exit(0);
}

const sectionFiles = walkDir(sectionsDir);
const entries: Array<{ key: string; meta: SectionMeta; filePath: string }> = [];

for (const filePath of sectionFiles) {
  const content = fs.readFileSync(filePath, "utf-8");
  const meta = extractMeta(content);
  if (!meta) continue;
  const key = fileToSectionKey(filePath, sectionsDir);
  entries.push({ key, meta, filePath });
}

const syncEntries = entries.filter((e) => e.meta.sync);
const fallbackEntries = entries.filter((e) => e.meta.hasLoadingFallback);

const lines: string[] = [
  "// Auto-generated by @decocms/start/scripts/generate-sections.ts",
  "// Do not edit manually. Add convention exports to your section files instead.",
  "//",
  "// Supported conventions:",
  "//   export const eager = true       → always SSR'd (never deferred)",
  "//   export const cache = \"listing\"  → SWR-cached section loader results",
  "//   export const layout = true      → cached as layout (Header, Footer, Theme)",
  "//   export const sync = true        → bundled synchronously (not lazy-loaded)",
  "//   export const clientOnly = true  → skip SSR (client-only rendering)",
  "//   export const seo = true         → SEO section (provides page head data)",
  "//   export function LoadingFallback → skeleton shown while section loads",
  "",
];

// Sync imports — sections marked sync=true get static imports for registerSectionsSync
for (let i = 0; i < syncEntries.length; i++) {
  const e = syncEntries[i];
  const importPath = relativeImportPath(outFile, e.filePath);
  const varName = `_sync${i}`;
  lines.push(`import * as ${varName} from "${importPath}";`);
}

// LoadingFallback imports — sections with LoadingFallback that aren't sync-imported
const nonSyncFallbacks = fallbackEntries.filter((e) => !e.meta.sync);
for (let i = 0; i < nonSyncFallbacks.length; i++) {
  const e = nonSyncFallbacks[i];
  const importPath = relativeImportPath(outFile, e.filePath);
  lines.push(`import { LoadingFallback as _fb${i} } from "${importPath}";`);
}

lines.push("");

// Metadata map
lines.push("export interface SectionMetaEntry {");
lines.push("  eager?: boolean;");
lines.push("  cache?: string;");
lines.push("  layout?: boolean;");
lines.push("  sync?: boolean;");
lines.push("  clientOnly?: boolean;");
lines.push("  seo?: boolean;");
lines.push("  hasLoadingFallback?: boolean;");
lines.push("}");
lines.push("");
lines.push("export const sectionMeta: Record<string, SectionMetaEntry> = {");
for (const e of entries) {
  const props = Object.entries(e.meta)
    .map(([k, v]) => `${k}: ${typeof v === "string" ? `"${v}"` : v}`)
    .join(", ");
  lines.push(`  "${e.key}": { ${props} },`);
}
lines.push("};");
lines.push("");

// Sync components map
if (syncEntries.length > 0) {
  lines.push("export const syncComponents: Record<string, any> = {");
  for (let i = 0; i < syncEntries.length; i++) {
    lines.push(`  "${syncEntries[i].key}": _sync${i},`);
  }
  lines.push("};");
} else {
  lines.push("export const syncComponents: Record<string, any> = {};");
}
lines.push("");

// LoadingFallback components map
const allFallbacks = entries.filter((e) => e.meta.hasLoadingFallback);
if (allFallbacks.length > 0) {
  lines.push("export const loadingFallbacks: Record<string, React.ComponentType<any>> = {");
  for (const e of allFallbacks) {
    if (e.meta.sync) {
      const syncIdx = syncEntries.indexOf(e);
      lines.push(`  "${e.key}": _sync${syncIdx}.LoadingFallback,`);
    } else {
      const fbIdx = nonSyncFallbacks.indexOf(e);
      lines.push(`  "${e.key}": _fb${fbIdx},`);
    }
  }
  lines.push("};");
} else {
  lines.push("export const loadingFallbacks: Record<string, React.ComponentType<any>> = {};");
}
lines.push("");

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join("\n"));

console.log(
  `Generated section metadata for ${entries.length} sections → ${path.relative(process.cwd(), outFile)}`,
);
console.log(
  `  ${syncEntries.length} sync, ${allFallbacks.length} with LoadingFallback, ` +
  `${entries.filter((e) => e.meta.eager).length} eager, ` +
  `${entries.filter((e) => e.meta.layout).length} layout, ` +
  `${entries.filter((e) => e.meta.cache).length} cached`,
);
