import * as fs from "node:fs";
import * as path from "node:path";
import type { MigrationContext } from "./types.ts";
import { logPhase } from "./types.ts";

const FRAMEWORK_FINDINGS = [
  "Session/analytics SDK is boilerplate duplicated across all sites — should be a single framework function",
  "GTM event system (useGTMEvent, data-gtm-* listeners) is universal pattern — should be in @decocms/start",
  "Route files (__root.tsx, index.tsx, $.tsx, deco/*) are near-identical across sites — should be generated by framework",
  "server.ts, worker-entry.ts, router.tsx are pure boilerplate — should be a single createSite() call",
  "setup.ts section registration via import.meta.glob is 100% boilerplate — framework should handle this",
  "runtime.ts invoke proxy is identical across sites — already in @decocms/start but sites still have local copies",
  "apps/site.ts is mostly empty after migration — platform config should be in a config file, not code",
];

export function report(ctx: MigrationContext): void {
  logPhase("Report");

  ctx.frameworkFindings = FRAMEWORK_FINDINGS;

  const lines: string[] = [];

  lines.push("# Migration Report");
  lines.push("");
  lines.push(`**Site:** ${ctx.siteName}`);
  lines.push(`**Platform:** ${ctx.platform}`);
  lines.push(`**GTM ID:** ${ctx.gtmId || "none"}`);
  lines.push(`**Date:** ${new Date().toISOString().split("T")[0]}`);
  lines.push(`**Mode:** ${ctx.dryRun ? "DRY RUN" : "EXECUTED"}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Files analyzed | ${ctx.files.length} |`);
  lines.push(`| Files scaffolded | ${ctx.scaffoldedFiles.length} |`);
  lines.push(`| Files transformed | ${ctx.transformedFiles.length} |`);
  lines.push(`| Files deleted | ${ctx.deletedFiles.length} |`);
  lines.push(`| Files moved | ${ctx.movedFiles.length} |`);
  lines.push(
    `| Manual review items | ${ctx.manualReviewItems.length} |`,
  );
  lines.push("");

  // Scaffolded files
  lines.push("## Scaffolded Files (new)");
  lines.push("");
  for (const f of ctx.scaffoldedFiles) {
    lines.push(`- \`${f}\``);
  }
  lines.push("");

  // Transformed files
  lines.push("## Transformed Files");
  lines.push("");
  for (const f of ctx.transformedFiles) {
    lines.push(`- \`${f}\``);
  }
  lines.push("");

  // Deleted files
  lines.push("## Deleted Files");
  lines.push("");
  for (const f of ctx.deletedFiles) {
    lines.push(`- \`${f}\``);
  }
  lines.push("");

  // Moved files
  if (ctx.movedFiles.length > 0) {
    lines.push("## Moved Files");
    lines.push("");
    for (const { from, to } of ctx.movedFiles) {
      lines.push(`- \`${from}\` → \`${to}\``);
    }
    lines.push("");
  }

  // Manual review
  if (ctx.manualReviewItems.length > 0) {
    lines.push("## Manual Review Required");
    lines.push("");
    for (const item of ctx.manualReviewItems) {
      const icon = item.severity === "error"
        ? "🔴"
        : item.severity === "warning"
        ? "🟡"
        : "🔵";
      lines.push(`${icon} **\`${item.file}\`**: ${item.reason}`);
    }
    lines.push("");
  }

  // Always-present manual review items
  lines.push("## Always Check (site-specific)");
  lines.push("");
  lines.push(
    "- [ ] `FormEmail.tsx` — `invoke.resend.actions.emails.send()` needs new server function pattern",
  );
  lines.push(
    "- [ ] `Slider.tsx` — verify `scriptAsDataURI` pattern works with React",
  );
  lines.push(
    "- [ ] `Theme.tsx` — verify `SiteTheme` mapping to `@decocms/start`",
  );
  lines.push("- [ ] DaisyUI v4 → v5 class name changes");
  lines.push(
    "- [ ] Tailwind v3 → v4: verify all utility classes still work",
  );
  lines.push(
    "- [ ] Check `src/styles/app.css` theme colors match the original design",
  );
  lines.push("");

  // Framework findings
  lines.push("## Framework Findings");
  lines.push("");
  lines.push(
    "> These are patterns found during migration that should eventually be handled by `@decocms/start` instead of being duplicated in every site.",
  );
  lines.push("");
  for (const finding of ctx.frameworkFindings) {
    lines.push(`- ${finding}`);
  }
  lines.push("");

  // Next steps
  lines.push("## Next Steps");
  lines.push("");
  lines.push("```bash");
  lines.push("# 1. Install dependencies");
  lines.push("npm install");
  lines.push("");
  lines.push("# 2. Generate CMS blocks and schema");
  lines.push("npm run generate:blocks");
  lines.push("npm run generate:schema");
  lines.push("");
  lines.push("# 3. Generate routes");
  lines.push("npx tsr generate");
  lines.push("");
  lines.push("# 4. Type check");
  lines.push("npx tsc --noEmit");
  lines.push("");
  lines.push("# 5. Find unused code");
  lines.push("npm run knip");
  lines.push("");
  lines.push("# 6. Run dev server");
  lines.push("npm run dev");
  lines.push("```");
  lines.push("");

  const content = lines.join("\n");

  if (ctx.dryRun) {
    console.log("\n" + content);
  } else {
    const reportPath = path.join(ctx.sourceDir, "MIGRATION_REPORT.md");
    fs.writeFileSync(reportPath, content, "utf-8");
    console.log(`  Report written to MIGRATION_REPORT.md`);
  }

  // Print summary to console
  console.log(`\n  === Migration ${ctx.dryRun ? "(DRY RUN)" : "COMPLETE"} ===`);
  console.log(`  Scaffolded: ${ctx.scaffoldedFiles.length}`);
  console.log(`  Transformed: ${ctx.transformedFiles.length}`);
  console.log(`  Deleted: ${ctx.deletedFiles.length}`);
  console.log(`  Moved: ${ctx.movedFiles.length}`);
  console.log(`  Manual review: ${ctx.manualReviewItems.length}`);
}
